# Welcome to Jekyll!
#

# Site settings
title: Tuan Nguyen
description: |
  
owner: Tuan Nguyen
first_published: 2017 # if migrating another site, the year of your first publish
email: tuan.d.nguyen@vanderbilt.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tuan-d-nguyen.github.io/" # the base hostname & protocol for your site
social:
  github: https://github.com/tuan-d-nguyen
  #linkedin-square: https://linkedin.com/in/kate-nelson-70ba8346
  #email: 
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
